# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "3691f7ef-8726-4cdd-a6df-ac92e8f2a972",
# META       "default_lakehouse_name": "lh_atlas_dev",
# META       "default_lakehouse_workspace_id": "7da777a8-e7db-4c0a-9423-3c91eaad9dda",
# META       "known_lakehouses": [
# META         {
# META           "id": "3691f7ef-8726-4cdd-a6df-ac92e8f2a972"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# # Atlas Trading Intelligence Platform
# ## Notebook: nb_gold_ai_market_commentary
# ### Release: v0.9.0 – AI Market Commentary & LLM Integration
# 
# ---
# 
# ### Purpose
# 
# This notebook performs Large Language Model (LLM) inference using the deterministic analytical features generated by the Atlas AI Intelligence Layer.
# 
# The notebook reads the `gold_ai_session_summary` Delta table, submits the prepared prompt template to a configurable AI provider, generates concise market commentary, and persists the resulting commentary together with inference metadata.
# 
# Unlike previous Gold and AI feature engineering notebooks, this notebook is **non-deterministic** because output depends upon the behaviour of the selected language model.
# 
# ---
# 
# ### Architectural Responsibilities
# 
# This notebook is responsible for:
# 
# - Reading deterministic AI-ready market features
# - Validating the upstream AI feature contract
# - Preparing AI inference requests
# - Calling a configurable AI provider through an abstraction layer
# - Generating concise natural-language market commentary
# - Recording inference metadata for traceability and auditing
# - Persisting AI commentary as a Delta table
# - Validating the generated output before completion
# 
# This notebook is **not responsible** for:
# 
# - Market data ingestion
# - Feature engineering
# - Technical indicator calculation
# - Trading signals
# - Forecasting
# - Buy or sell recommendations
# - Modifying deterministic analytical outputs
# 
# ---
# 
# ### Input
# 
# Delta Table:
# 
# - `gold_ai_session_summary`
# 
# ---
# 
# ### Output
# 
# Delta Table:
# 
# - `gold_ai_market_commentary`
# 
# ---
# 
# ### Supported AI Providers
# 
# The notebook has been designed with a provider abstraction layer allowing future integration with multiple AI services, including:
# 
# - Microsoft Fabric AI
# - Azure OpenAI
# - Phi
# - Other compatible LLM providers
# 
# The provider implementation can be changed without affecting upstream deterministic analytics.
# 
# ---
# 
# ### Atlas Architecture
# 
# ```
# Market Data
#       │
#       ▼
#  Bronze Layer
#       │
#       ▼
#  Silver Layer
#       │
#       ▼
#  Gold Analytics
#       │
#       ▼
# AI Session Summary
# (Deterministic Features)
#       │
#       ▼
# Contract Validation
#       │
#       ▼
# Provider Abstraction
#       │
#       ▼
# LLM Inference
#       │
#       ▼
# Output Validation
#       │
#       ▼
# gold_ai_market_commentary
#       │
#       ▼
# Direct Lake Semantic Model
#       │
#       ▼
# Power BI Reports
# ```
# 
# ---
# 
# ### Engineering Principles
# 
# - Deterministic feature engineering remains isolated from AI inference.
# - AI inference is accessed through a provider abstraction layer to support interchangeable LLM providers.
# - Upstream analytical contracts are validated before inference begins.
# - Commentary generation is traceable through prompt versioning, input hashing and inference metadata.
# - Output contracts are validated before publication.
# - Failure of an external AI service must not compromise upstream analytics.
# - Generated commentary is persisted as a Delta table for reporting, auditing and future model evaluation.
# 
# ---
# 
# **Atlas Trading Intelligence Platform**  
# Version: **v0.9.0 – AI Market Commentary & LLM Integration**


# CELL ********************

# ============================================================
# Atlas Trading Intelligence Platform
# Configuration
# Notebook: nb_gold_ai_market_commentary
# Release: v0.9.0
# ============================================================

from datetime import datetime, timezone

# ------------------------------------------------------------
# Input / Output Tables
# ------------------------------------------------------------

SOURCE_TABLE = "gold_ai_session_summary"
TARGET_TABLE = "gold_ai_market_commentary"

# ------------------------------------------------------------
# AI Provider Configuration
# ------------------------------------------------------------

class AIProvider:
    STUB = "Stub"
    FABRIC = "FabricAI"
    AZURE_OPENAI = "AzureOpenAI"
    PHI = "Phi"

AI_PROVIDER = AIProvider.STUB          # Stub | FabricAI | AzureOpenAI | Phi
MODEL_NAME = "DeterministicStub-v1"

# ------------------------------------------------------------
# Prompt Configuration
# ------------------------------------------------------------

PROMPT_VERSION = "1.0"

# ------------------------------------------------------------
# Notebook Metadata
# ------------------------------------------------------------

NOTEBOOK_NAME = "nb_gold_ai_market_commentary"
SOURCE_NOTEBOOK = "nb_gold_ai_session_summary"

# ------------------------------------------------------------
# Runtime Metadata
# ------------------------------------------------------------

RUN_UTC = datetime.now(timezone.utc)

print("Atlas Trading Intelligence Platform")
print("-----------------------------------")
print(f"Source Table   : {SOURCE_TABLE}")
print(f"Target Table   : {TARGET_TABLE}")
print(f"AI Provider    : {AI_PROVIDER}")
print(f"Model Name     : {MODEL_NAME}")
print(f"Prompt Version : {PROMPT_VERSION}")
print(f"Run UTC        : {RUN_UTC}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# Imports and Helper Functions
# ============================================================

from pyspark.sql import DataFrame
from pyspark.sql.functions import (
    col,
    lit,
    current_timestamp,
    sha2,
    concat_ws,
    coalesce
)

# ------------------------------------------------------------
# Helper: Table Existence Check
# ------------------------------------------------------------

def table_exists(table_name: str) -> bool:
    """
    Check whether a table exists in the current Lakehouse context.
    """
    try:
        spark.table(table_name)
        return True
    except Exception:
        return False


# ------------------------------------------------------------
# Helper: Display DataFrame Summary
# ------------------------------------------------------------

def display_dataframe_summary(df: DataFrame, dataframe_name: str) -> None:
    """
    Display basic record count and schema information for a DataFrame.
    """
    row_count = df.count()

    print(f"DataFrame: {dataframe_name}")
    print(f"Row Count : {row_count}")
    print("Schema:")
    df.printSchema()


# ------------------------------------------------------------
# Helper: Validate Required Columns
# ------------------------------------------------------------

def validate_required_columns(df: DataFrame, required_columns: list[str], dataframe_name: str) -> None:
    """
    Validate that a DataFrame contains all required columns.
    """
    missing_columns = [column for column in required_columns if column not in df.columns]

    if missing_columns:
        raise ValueError(
            f"{dataframe_name} is missing required columns: {missing_columns}"
        )

    print(f"{dataframe_name} contains all required columns.")


# ------------------------------------------------------------
# Helper: Build Input Hash
# ------------------------------------------------------------

def add_input_hash(df: DataFrame) -> DataFrame:
    """
    Add a stable hash representing the deterministic input used for commentary generation.
    This allows generated commentary to be traced back to a specific analytical input state.
    """
    return df.withColumn(
        "InputHash",
        sha2(
            concat_ws(
                "||",
                coalesce(col("Instrument").cast("string"), lit("")),
                coalesce(col("TradingDate").cast("string"), lit("")),
                coalesce(col("PromptVersion").cast("string"), lit("")),
                coalesce(col("PromptTemplate").cast("string"), lit(""))
            ),
            256
        )
    )


print("Imports and helper functions loaded successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# Read Source Table
# ============================================================

print(f"Reading source table: {SOURCE_TABLE}")

# ------------------------------------------------------------
# Validate Source Table Exists
# ------------------------------------------------------------

if not table_exists(SOURCE_TABLE):
    raise RuntimeError(
        f"Source table '{SOURCE_TABLE}' was not found."
    )

print("Source table found.")

# ------------------------------------------------------------
# Read Source Data
# ------------------------------------------------------------

df_session_summary = spark.table(SOURCE_TABLE)

print("Source table loaded successfully.")

# ------------------------------------------------------------
# Display Summary
# ------------------------------------------------------------

display_dataframe_summary(
    df_session_summary,
    "gold_ai_session_summary"
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# Validate Input Data
# ============================================================

print("Validating source data...")

# ------------------------------------------------------------
# Required Columns
# ------------------------------------------------------------

required_columns = [
    "Instrument",
    "TradingDate",
    "PromptVersion",
    "PromptTemplate",
    "PriceDirection",
    "SessionDirection",
    "VolatilityBand",
    "ActivityBand",
    "SessionCharacter",
    "DailyRangePct",
    "DailyReturnPct"
]

validate_required_columns(
    df_session_summary,
    required_columns,
    "gold_ai_session_summary"
)

# ------------------------------------------------------------
# Validate Row Count
# ------------------------------------------------------------

record_count = df_session_summary.count()

if record_count == 0:
    raise RuntimeError(
        f"Source table '{SOURCE_TABLE}' contains no records."
    )

print(f"Source table contains {record_count:,} records.")

# ------------------------------------------------------------
# Validate Prompt Templates
# ------------------------------------------------------------

missing_prompts = (
    df_session_summary
    .filter(
        col("PromptTemplate").isNull() |
        (col("PromptTemplate") == "")
    )
    .count()
)

if missing_prompts > 0:
    raise RuntimeError(
        f"{missing_prompts} record(s) contain a missing PromptTemplate."
    )

print("All records contain a valid PromptTemplate.")

# ------------------------------------------------------------
# Add Input Hash
# ------------------------------------------------------------

df_session_summary = add_input_hash(df_session_summary)

print("InputHash column generated successfully.")

print("Input validation completed successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# AI Provider Interface
# ============================================================

print("Initialising AI provider interface...")

# ------------------------------------------------------------
# Helper: Build Stub Commentary
# ------------------------------------------------------------

def generate_stub_commentary(row) -> str:
    """
    Generate deterministic placeholder commentary from analytical features.

    This is used to validate the AI inference architecture before integrating
    with an external LLM provider such as Fabric AI or Azure OpenAI.
    """
    return (
        f"{row['Instrument']} traded {row['PriceDirection'].lower()} on "
        f"{row['TradingDate']}. The session was classified as a "
        f"{row['SessionCharacter']}, with {row['VolatilityBand'].lower()} "
        f"volatility and {row['ActivityBand'].lower()} trading activity."
    )


# ------------------------------------------------------------
# Helper: Generate Market Commentary
# ------------------------------------------------------------

def generate_market_commentary(row) -> dict:
    """
    Generate market commentary using the configured AI provider.

    The notebook calls this function without needing to know which provider
    generated the commentary. This keeps AI inference isolated from the
    orchestration logic.
    """
    try:
        if AI_PROVIDER == AIProvider.STUB:
            commentary = generate_stub_commentary(row)

            return {
                "Commentary": commentary,
                "InferenceStatus": "Succeeded",
                "InferenceError": None,
                "ModelProvider": AI_PROVIDER,
                "ModelName": MODEL_NAME
            }

        elif AI_PROVIDER == AIProvider.FABRIC:
            raise NotImplementedError(
                "Fabric AI provider has not yet been implemented."
            )

        elif AI_PROVIDER == AIProvider.AZURE_OPENAI:
            raise NotImplementedError(
                "Azure OpenAI provider has not yet been implemented."
            )

        elif AI_PROVIDER == AIProvider.PHI:
            raise NotImplementedError(
                "Phi provider has not yet been implemented."
            )

        else:
            raise ValueError(f"Unsupported AI provider: {AI_PROVIDER}")

    except Exception as error:
        return {
            "Commentary": None,
            "InferenceStatus": "Failed",
            "InferenceError": str(error),
            "ModelProvider": AI_PROVIDER,
            "ModelName": MODEL_NAME
        }


print(f"AI provider interface initialised successfully: {AI_PROVIDER}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# Generate Commentary
# ============================================================

print("Generating market commentary...")

# ------------------------------------------------------------
# Convert Source Rows for Provider Processing
# ------------------------------------------------------------

source_rows = df_session_summary.collect()

commentary_results = []

# ------------------------------------------------------------
# Generate Commentary Per Session
# ------------------------------------------------------------

for row in source_rows:
    result = generate_market_commentary(row)

    commentary_results.append({
        "Instrument": row["Instrument"],
        "TradingDate": row["TradingDate"],
        "PromptVersion": row["PromptVersion"],
        "PromptTemplate": row["PromptTemplate"],
        "InputHash": row["InputHash"],
        "Commentary": result["Commentary"],
        "InferenceStatus": result["InferenceStatus"],
        "InferenceError": result["InferenceError"],
        "ModelProvider": result["ModelProvider"],
        "ModelName": result["ModelName"],
        "GeneratedUTC": RUN_UTC,
        "SourceTable": SOURCE_TABLE,
        "SourceNotebook": SOURCE_NOTEBOOK
    })

# ------------------------------------------------------------
# Validate Commentary Result Count
# ------------------------------------------------------------

if len(commentary_results) == 0:
    raise RuntimeError("No commentary results were generated.")

print(f"Generated commentary for {len(commentary_results):,} session(s).")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# Build Output DataFrame
# ============================================================

print("Building output DataFrame...")

from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    DateType,
    TimestampType
)

# ------------------------------------------------------------
# Define Output Schema
# ------------------------------------------------------------

market_commentary_schema = StructType([
    StructField("Instrument", StringType(), True),
    StructField("TradingDate", DateType(), True),
    StructField("PromptVersion", StringType(), True),
    StructField("PromptTemplate", StringType(), True),
    StructField("InputHash", StringType(), True),
    StructField("Commentary", StringType(), True),
    StructField("InferenceStatus", StringType(), True),
    StructField("InferenceError", StringType(), True),
    StructField("ModelProvider", StringType(), True),
    StructField("ModelName", StringType(), True),
    StructField("GeneratedUTC", TimestampType(), True),
    StructField("SourceTable", StringType(), True),
    StructField("SourceNotebook", StringType(), True)
])

# ------------------------------------------------------------
# Create Spark DataFrame from Commentary Results
# ------------------------------------------------------------

df_market_commentary = spark.createDataFrame(
    commentary_results,
    schema=market_commentary_schema
)

# ------------------------------------------------------------
# Select Final Output Columns
# ------------------------------------------------------------

df_market_commentary = df_market_commentary.select(
    "Instrument",
    "TradingDate",
    "PromptVersion",
    "PromptTemplate",
    "InputHash",
    "Commentary",
    "InferenceStatus",
    "InferenceError",
    "ModelProvider",
    "ModelName",
    "GeneratedUTC",
    "SourceTable",
    "SourceNotebook"
)

# ------------------------------------------------------------
# Display Output Summary
# ------------------------------------------------------------

display_dataframe_summary(
    df_market_commentary,
    "gold_ai_market_commentary"
)

print("Output DataFrame built successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# Write Delta Table
# ============================================================

print(f"Writing output table: {TARGET_TABLE}")

# ------------------------------------------------------------
# Write Market Commentary Table
# ------------------------------------------------------------

(
    df_market_commentary
    .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(TARGET_TABLE)
)

print(f"Output table written successfully: {TARGET_TABLE}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ============================================================
# Validation
# ============================================================

print("Validating generated market commentary...")

# ------------------------------------------------------------
# Read Output Table
# ------------------------------------------------------------

df_validation = spark.table(TARGET_TABLE)

# ------------------------------------------------------------
# Display Summary
# ------------------------------------------------------------

display_dataframe_summary(
    df_validation,
    TARGET_TABLE
)

# ------------------------------------------------------------
# Validation Metrics
# ------------------------------------------------------------

total_records = df_validation.count()

successful_inference = (
    df_validation
    .filter(col("InferenceStatus") == "Succeeded")
    .count()
)

failed_inference = (
    df_validation
    .filter(col("InferenceStatus") == "Failed")
    .count()
)

print()
print("Validation Results")
print("------------------")
print(f"Total Records        : {total_records:,}")
print(f"Successful Inference : {successful_inference:,}")
print(f"Failed Inference     : {failed_inference:,}")

# ------------------------------------------------------------
# Display Sample Results
# ------------------------------------------------------------

print()
print("Sample Market Commentary")

display(
    df_validation
    .select(
        "Instrument",
        "TradingDate",
        "Commentary",
        "ModelProvider",
        "ModelName",
        "InferenceStatus"
    )
    .orderBy("TradingDate")
)

print()
print("Notebook completed successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Notes / Future Provider Integration
# 
# This notebook currently uses the `Stub` AI provider to validate the end-to-end inference architecture without requiring an external LLM service.
# 
# The stub provider confirms that the notebook can:
# 
# - read deterministic AI-ready features
# - validate the source contract
# - generate commentary output
# - apply provider abstraction
# - record inference metadata
# - persist results to Delta
# - validate the generated commentary table
# 
# ## Future Provider Integration
# 
# Future releases can replace the stub implementation inside `generate_market_commentary()` with a real AI provider while leaving the rest of the notebook unchanged.
# 
# Candidate providers include:
# 
# - Microsoft Fabric AI
# - Azure OpenAI
# - Phi
# - Other compatible LLM providers
# 
# ## Planned Integration Pattern
# 
# Future provider implementation should preserve the existing contract:
# 
# ```python
# {
#     "Commentary": "...",
#     "InferenceStatus": "Succeeded",
#     "InferenceError": None,
#     "ModelProvider": "...",
#     "ModelName": "..."
# }

