/// Original tabled is called gold_cqg_daily_candles
table 'Daily Candles'
	lineageTag: fd934c6c-8bb1-4bb2-8e9e-18bc8cfd56ce
	sourceLineageTag: [dbo].[gold_cqg_daily_candles]

	measure 'Total Trades' =
			
			SUM('Daily Candles'[TotalTrades])
		formatString: #,0
		displayFolder: Measures
		lineageTag: 7cde381e-7d8f-4ab4-ba15-889f48ccf564

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Trading Days' =
			
			DISTINCTCOUNT ( 'Daily Candles'[TradingDate] )
		formatString: 0
		displayFolder: Measures
		lineageTag: aa10e8d1-2347-4b80-83ea-33e6fa55579d

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Average Trades / Day' =
			
			DIVIDE([Total Trades], [Trading Days])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: decf2227-7484-489e-95df-21751c89f8c5

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Daily Range' =
			
			[Selected Period High] - [Selected Period Low]
		formatString: 0.00000
		displayFolder: Statistics
		lineageTag: 8a2ecc78-8fce-40cc-8d9a-3174b706a51d

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Daily Range %' =
			
			DIVIDE (
			    [Daily Range],
			    [Selected Period Open]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Statistics
		lineageTag: 17818e22-e8f1-485b-9084-83b46ed1bda5

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure '5-Day MA Close' =
			
			VAR CurrentDate =
			    MAX ( 'Daily Candles'[TradingDate] )
			VAR Last5TradingDays =
			    TOPN (
			        5,
			        FILTER (
			            ALLSELECTED ( 'Daily Candles' ),
			            'Daily Candles'[Instrument] = MAX ( 'Daily Candles'[Instrument] )
			                && 'Daily Candles'[TradingDate] <= CurrentDate
			        ),
			        'Daily Candles'[TradingDate],
			        DESC
			    )
			RETURN
			    AVERAGEX (
			        Last5TradingDays,
			        'Daily Candles'[Close]
			    )
		formatString: 0.00000
		displayFolder: Indicators
		lineageTag: 5993628b-2688-47ba-8674-add876cdd5f6

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Selected Period Return %' =
			
			DIVIDE (
			    [Selected Period Close] - [Selected Period Open],
			    [Selected Period Open]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Statistics
		lineageTag: e14e4eb6-7905-491b-b1ee-049f071279a5

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Selected Period Open' =
			
			VAR FirstTradingDate =
			    MIN ( 'Daily Candles'[TradingDate] )
			RETURN
			    CALCULATE (
			        MAX ( 'Daily Candles'[Open] ),
			        'Daily Candles'[TradingDate] = FirstTradingDate
			    )
		formatString: 0.00000
		displayFolder: Price
		lineageTag: 12a07783-58ac-4d73-a0e4-1287b243212c

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Selected Period Close' =
			
			VAR LastTradingDate =
			    MAX ( 'Daily Candles'[TradingDate] )
			RETURN
			    CALCULATE (
			        MAX ( 'Daily Candles'[Close] ),
			        'Daily Candles'[TradingDate] = LastTradingDate
			    )
		formatString: 0.00000
		displayFolder: Price
		lineageTag: 40032ec4-6203-4774-9fd3-43f3fbf760e5

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Selected Period High' =
			
			MAX ( 'Daily Candles'[High] )
		formatString: 0.00000
		displayFolder: Price
		lineageTag: 318cb57b-7f60-45e7-ba3a-9ded29db8643

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Selected Period Low' =
			
			MIN ( 'Daily Candles'[Low] )
		formatString: 0.00000
		displayFolder: Price
		lineageTag: a00de683-717a-4aef-8296-01510d1bc1fb

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Selected Trading Date' =
			
			MAX ( 'gold_dim_date'[Date] )
		formatString: Short Date
		displayFolder: Time Intelligence
		lineageTag: 677213b7-899b-4425-880d-d547210c0b29

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Previous Trading Date' =
			
			VAR CurrentDate =
			    [Selected Trading Date]
			RETURN
			    CALCULATE (
			        MAX ( 'Daily Candles'[TradingDate] ),
			        REMOVEFILTERS ( 'gold_dim_date' ),
			        'Daily Candles'[TradingDate] < CurrentDate
			    )
		formatString: Short Date
		displayFolder: Time Intelligence
		lineageTag: 493ae585-7f2e-46f3-ac24-67e9fe1c0364

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Previous Trading Day Close' =
			
			VAR PreviousDate =
			    [Previous Trading Date]
			RETURN
			    CALCULATE (
			        MAX ( 'Daily Candles'[Close] ),
			        REMOVEFILTERS ( 'gold_dim_date' ),
			        'Daily Candles'[TradingDate] = PreviousDate
			    )
		formatString: 0.00000
		displayFolder: Time Intelligence
		lineageTag: 4a229a86-6120-4918-9d45-485077f236a4

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Selected Trading Day Close' =
			
			VAR CurrentDate =
			    [Selected Trading Date]
			RETURN
			    CALCULATE (
			        MAX ( 'Daily Candles'[Close] ),
			        REMOVEFILTERS ( 'gold_dim_date' ),
			        'Daily Candles'[TradingDate] = CurrentDate
			    )
		formatString: 0.00000
		displayFolder: Time Intelligence
		lineageTag: b40cc2fb-706c-4067-adf3-95719e6d5cc0

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Trading Day Change' =
			
			[Selected Trading Day Close] - [Previous Trading Day Close]
		formatString: 0.00000
		displayFolder: Time Intelligence
		lineageTag: 266b36e3-ba89-4e3b-87d1-e45f27748189

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	measure 'Trading Day Change %' =
			
			DIVIDE (
			    [Trading Day Change],
			    [Previous Trading Day Close]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time Intelligence
		lineageTag: 4f1e124c-1b3a-43b4-b373-44e30d630139

		changedProperty = Name

		changedProperty = DisplayFolder

		changedProperty = FormatString

	/// Financial instrument symbol for the aggregated candlestick.
	column Instrument
		dataType: string
		displayFolder: Trading
		lineageTag: 6ec51ca4-15e1-4518-8442-9e976cc7a809
		sourceLineageTag: Instrument
		summarizeBy: none
		sourceColumn: Instrument

		changedProperty = Description

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	/// Trading date associated with the daily candlestick.
	column TradingDate
		dataType: dateTime
		formatString: Short Date
		displayFolder: Trading
		lineageTag: e041c65b-ad32-44eb-ae46-4096a3ab34bb
		sourceLineageTag: TradingDate
		summarizeBy: none
		sourceColumn: TradingDate

		changedProperty = FormatString

		changedProperty = Description

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	/// First traded price recorded during the trading day.
	column Open
		dataType: double
		formatString: 0.00000
		displayFolder: Price
		lineageTag: 8ca2b899-7442-4884-ac60-db3f19a7da77
		sourceLineageTag: Open
		summarizeBy: none
		sourceColumn: Open

		changedProperty = SummarizeBy

		changedProperty = FormatString

		changedProperty = Description

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = User

	/// Highest traded price recorded during the trading day.
	column High
		dataType: double
		formatString: 0.00000
		displayFolder: Price
		lineageTag: dd52b1b2-ed6f-47bb-a975-a106dad2d550
		sourceLineageTag: High
		summarizeBy: none
		sourceColumn: High

		changedProperty = SummarizeBy

		changedProperty = FormatString

		changedProperty = Description

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = User

	/// Lowest traded price recorded during the trading day.
	column Low
		dataType: double
		formatString: 0.00000
		displayFolder: Price
		lineageTag: a7d42664-7855-4419-a92f-72c3cd43d66a
		sourceLineageTag: Low
		summarizeBy: none
		sourceColumn: Low

		changedProperty = SummarizeBy

		changedProperty = FormatString

		changedProperty = Description

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = User

	/// Last traded price recorded during the trading day.
	column Close
		dataType: double
		formatString: 0.00000
		displayFolder: Price
		lineageTag: a22a712b-aa30-42b7-9010-c433bbf642a8
		sourceLineageTag: Close
		summarizeBy: none
		sourceColumn: Close

		changedProperty = SummarizeBy

		changedProperty = FormatString

		changedProperty = Description

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = User

	/// Total number of CQG tick events aggregated into the daily candlestick.
	column TotalTrades
		dataType: int64
		formatString: #,0
		displayFolder: Statistics
		lineageTag: ef6db50e-296b-4911-9988-b47cb16dde32
		sourceLineageTag: TotalTrades
		summarizeBy: sum
		sourceColumn: TotalTrades

		changedProperty = FormatString

		changedProperty = Description

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column GoldLoadedUTC
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 069d72e0-8313-456a-9e60-8973ffe48928
		sourceLineageTag: GoldLoadedUTC
		summarizeBy: none
		sourceColumn: GoldLoadedUTC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Daily Candles' = entity
		mode: directLake
		source
			entityName: gold_cqg_daily_candles
			schemaName: dbo
			expressionSource: 'DirectLake - lh_atlas_dev'

	changedProperty = Description

	changedProperty = Name

